@baseUrl = http://localhost:7072/api/workrequests

### 1. Hent alle arbejdsforespørgsler
GET {{baseUrl}}
Accept: application/json


### 2. Opret en ny arbejdsforespørgsel
POST {{baseUrl}}/
Content-Type: application/json

{
  "fornavn": "Saniela",
  "efternavn": "Dhimitri",
  "email": "saniela0709@icloud.com",
  "telefon": "12345678",
  "adresse": "Gentofte",
  "beskrivelse": "Maling af lejlighed"
}


### 3. Hent arbejdsforespørgsel med ID 83
GET {{baseUrl}}/77
Accept: application/json

### 4. Opdater status på WorkRequest
PUT {{baseUrl}}/83/status
Content-Type: application/json

{
  "status": "UNDER_BEHANDLING"
}


### 5. Slet arbejdsforespørgsel med ID 82
DELETE {{baseUrl}}/82


### 6. Kontroller at WorkRequest er slettet
GET http://localhost:7072/api/workrequests/77
Accept: application/json

### 2. Opret en ny arbejdsforespørgsel
POST {{baseUrl}}/
Content-Type: application/json

{
  "fornavn": "Saniela",
  "efternavn": "Dhimitri",
  "email": "sadh1000@stud.ek.dk",
  "telefon": "12345678",
  "adresse": "Gentofte",
  "beskrivelse": "Maling af lejlighed"
}


###

POST http://localhost:7072/api/workrequests
Content-Type: application/json

{
  "fornavn": "Saniela",
  "efternavn": "Dhimitri",
  "email": "sadh1000@stud.ek.dk",
  "telefon": "12345678",
  "adresse": "Gentofte",
  "beskrivelse": "Maling af lejlighed"
}
###

POST http://localhost:7072/api/workrequests
Content-Type: application/json

{
  "fornavn": "Saniela",
  "efternavn": "Dhimitri",
  "email": "sadh1000@stud.ek.dk",
  "telefon": "12345678",
  "adresse": "Gentofte",
  "beskrivelse": "Maling af værelse"
}
